"""
PDF Sentinel - Report Generator
Generate printable verification reports.
"""

from datetime import datetime
from pathlib import Path
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
)


def generate_verification_report(
    file_name: str,
    verification_status: str,
    hash_value: str,
    timestamp: str,
    output_path: Optional[str | Path] = None
) -> str:
    """
    Generate a printable PDF verification report.
    
    Args:
        file_name: Name of the verified file
        verification_status: Status message
        hash_value: The SHA256 hash
        timestamp: When the file was stamped
        output_path: Where to save the report (defaults to temp location)
        
    Returns:
        Path to the generated report
    """
    if output_path is None:
        output_path = Path.cwd() / f"verification_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    else:
        output_path = Path(output_path)
    
    # Create the PDF document
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        rightMargin=2*cm,
        leftMargin=2*cm,
        topMargin=2*cm,
        bottomMargin=2*cm
    )
    
    # Styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'Title',
        parent=styles['Heading1'],
        fontSize=24,
        spaceAfter=30,
        alignment=1  # Center
    )
    
    subtitle_style = ParagraphStyle(
        'Subtitle',
        parent=styles['Normal'],
        fontSize=12,
        textColor=colors.grey,
        alignment=1
    )
    
    # Build the content
    content = []
    
    # Add Sentinel logo from icon.png
    import sys
    if getattr(sys, 'frozen', False):
        icon_path = Path(sys._MEIPASS) / "assets" / "icon.png"
    else:
        icon_path = Path(__file__).parent.parent / "assets" / "icon.png"
    
    if icon_path.exists():
        logo = Image(str(icon_path), width=1*inch, height=1*inch)
        logo.hAlign = 'CENTER'
        content.append(logo)
        content.append(Spacer(1, 20))
    
    # Header
    content.append(Paragraph("PDF Sentinel", title_style))
    content.append(Paragraph("Document Verification Report", subtitle_style))
    content.append(Spacer(1, 40))
    
    # Status banner
    is_verified = "verified" in verification_status.lower()
    status_color = colors.green if is_verified else colors.red
    status_text = "✓ VERIFIED" if is_verified else "✗ VERIFICATION FAILED"
    
    status_style = ParagraphStyle(
        'Status',
        parent=styles['Heading2'],
        fontSize=18,
        textColor=status_color,
        alignment=1
    )
    content.append(Paragraph(status_text, status_style))
    content.append(Spacer(1, 30))
    
    # Details table
    data = [
        ["Document:", file_name],
        ["Status:", verification_status],
        ["SHA256 Hash:", hash_value[:32] + "..." if len(hash_value) > 35 else hash_value],
        ["Stamped On:", timestamp],
        ["Report Generated:", datetime.now().isoformat()],
    ]
    
    table = Table(data, colWidths=[4*cm, 12*cm])
    table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('TOPPADDING', (0, 0), (-1, -1), 12),
        ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    
    content.append(table)
    content.append(Spacer(1, 40))
    
    # Full hash
    content.append(Paragraph("<b>Full Hash Value:</b>", styles['Normal']))
    content.append(Spacer(1, 10))
    
    hash_style = ParagraphStyle(
        'HashValue',
        parent=styles['Code'],
        fontSize=8,
        fontName='Courier',
        backColor=colors.lightgrey,
        borderPadding=10
    )
    content.append(Paragraph(hash_value, hash_style))
    content.append(Spacer(1, 40))
    
    # Footer note
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.grey,
        alignment=1
    )
    content.append(Paragraph(
        "This report was generated by PDF Sentinel. "
        "The SHA256 hash provides cryptographic proof of document integrity.",
        footer_style
    ))
    
    # Build the PDF
    doc.build(content)
    
    return str(output_path)
